---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pacti620/public_html/geekndragon.com/
    - /usr/bin/env composer install --no-dev --optimize-autoloader
    - /usr/bin/php build-sitemap.php
    - /usr/bin/rsync -av --delete --exclude='.git/' . "$DEPLOYPATH"
