---
deployment:
  tasks:
    # Deploy to the document root used by the live site.
    # The previous path pointed to /public_html/geekndragon.com which did not
    # match the path used at runtime (/home/pacti620/geekndragon.com).
    # As a result the "vendor" directory, including Composer's ClassLoader,
    # was missing and PHP failed to load the autoloader.
    - export DEPLOYPATH=/home/pacti620/geekndragon.com/
    # First sync the repository to the live document root.
    - /usr/bin/rsync -av --delete --exclude='.git/' . "$DEPLOYPATH"
    # Set production environment variable
    - /bin/sh -c 'printf "APP_ENV=production\n" > "$DEPLOYPATH/.env"'
    # Install Composer dependencies directly in the deploy path so the
    # vendor/composer/ClassLoader.php file is always available at runtime.
    - /usr/bin/env composer install --no-dev --optimize-autoloader -d "$DEPLOYPATH"
    # Rebuild the sitemap using the freshly installed autoloader.
    - /usr/bin/php "$DEPLOYPATH/build-sitemap.php"
